language: go
dist: trusty
sudo: false

matrix:
  include:
    - go: 1.8.3
    - go: 1.9
    - go: tip
  allow_failures:
    - go: tip

branches:
    only:
        - master
        - dev

script:
    - make
