language: go
go_import_path: github.com/bytom
dist: trusty
sudo: false

matrix:
  include:
    - go: 1.8.3
    - go: 1.9

branches:
    only:
        - master
        - dev
        - politic

script:
    - make ci
