name: go-unit-test
on:
#  push:
#    tags:
#      - v*
#    branches:
#      - master
  pull_request:
    tags:
      - v*
    branches:
      - master
      - dev
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        os: [ubuntu-latest, macos-latest]
    name: (${{ matrix.os }}, ${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::/home/runner/work/bytom/go"
          echo "::add-path::/home/runner/work/bytom/go/bin"

      - name: Unit test
        run: go test ./...

#      echo $(go list ./... | grep -v '/vendor/') && export GOPATH=$HOME/go && go test ./...
#          echo "hello"
#          echo ./...
#          echo $(go list ./... | grep -v '/vendor/')


#      - name: Run tests
#        shell: bash
#        run: |
#          export GO111MODULE=on
#          export GOPROXY=https://goproxy.cn
#          make test


#  go list ./...
#  shell: /bin/bash -e {0}
#  env:
#    GOROOT: /opt/hostedtoolcache/go/1.13.15/x64
#  _/home/runner/work/bytom/bytom/accesstoken
